### ISSUE TITLE
Add option for nag to always show

### ISSUE THREAD

**Issue by Rakizi** [Rakizi/NAG-issues#22]

**Comment by luismiguelgp1985** [comment]
The Ret NAG flickers during AoE rotations when switching targets. This happens because it's designed to display only when an enemy target is selected. When your current target dies, the NAG briefly disappears until you select a new target. Although this flicker lasts just a split second, it would be helpful to have an option for it to remain visible at all times.

**Comment by luismiguelgp1985** [comment]
![Screenshot 2024-09-08 121248](https://github.com/user-attachments/assets/5b5e671a-bcce-4903-9be5-a4729855aee7)
The guitar hero mana bar shows only when in combat. Please also make it show at all times.
